### ISSUE TITLE
Fabric has a standard tag for shears now

### ISSUE THREAD

**Issue by LemmaEOF** [Linguardium/ItemCompat#5]
The Fabric Tool Attributes API now has a `fabric:shears` tag for use with `.breakByTool`, which should probably be used for this mod as well. You can add a `fabric:shears` tag with `#c:shears` as an entry, which should make compat seamless.

**Comment by Linguardium** [comment]
Thanks! I may want to move to the standard fabric tag though and just add #c:shears to it (that way it doesnt draw people away from the standard tags)

**Comment by Linguardium** [comment]
updated in 7b55f1f
